-- BRS_Units_Property
-- Author: Sanakan
-- DateCreated: 1/12/2024 8:14:56 PM
--------------------------------------------------------------

INSERT INTO GameModifiers (ModifierId)
VALUES	-- LEADER BURNING EYE ABILITY
		('MODIFIER_ENABLE_BURNING_EYE_COMBAT_STRENGTH_PROPERTY'),
		('MODIFIER_ENABLE_BURNING_EYE_MOVEMENT_PROPERTY'),
		-- CIVILIZATION TWO WORLDS ABILITY
		('MODIFIER_ENABLE_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY');

INSERT INTO TraitModifiers (TraitType, ModifierId) -- add property to leader
SELECT TraitType, 'MODIFIER_ENABLE_BURNING_EYE_COMBAT_STRENGTH_PROPERTY' FROM LeaderTraits WHERE LeaderType = 'LEADER_SGA_BRS'
UNION ALL SELECT TraitType, 'MODIFIER_ENABLE_BURNING_EYE_MOVEMENT_PROPERTY' FROM LeaderTraits WHERE LeaderType = 'LEADER_SGA_BRS';

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES	('TRAIT_CIVILIZATION_SGA_BRS_TWO_WORLDS', 'MODIFIER_ENABLE_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent)
VALUES	-- LEADER BURNING EYE ABILITY
		('MODIFIER_BURNING_EYE_COMBAT_STRENGTH_PROPERTY', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 0, 0),
		('MODIFIER_ENABLE_BURNING_EYE_COMBAT_STRENGTH_PROPERTY', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 0, 0),
		('MODIFIER_BURNING_EYE_COMBAT_STRENGTH_ATTACHMENT', 'MODIFIER_UNIT_ADJUST_PROPERTY', 1, 1),
		--------------------------------------------------------------
		('MODIFIER_BURNING_EYE_MOVEMENT_PROPERTY', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 0, 0),
		('MODIFIER_ENABLE_BURNING_EYE_MOVEMENT_PROPERTY', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 0, 0),
		('MODIFIER_BURNING_EYE_MOVEMENT_ATTACHMENT', 'MODIFIER_UNIT_ADJUST_PROPERTY', 1, 1),
		-- CIVILIZATION TWO WORLDS ABILITY
		('MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 0, 0),
		('MODIFIER_ENABLE_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 0, 0),
		('MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_ATTACHMENT', 'MODIFIER_UNIT_ADJUST_PROPERTY', 1, 1);

INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES	-- LEADER BURNING EYE ABILITY
		('MODIFIER_BURNING_EYE_COMBAT_STRENGTH_PROPERTY', 'Key', 'BURNING_EYE_COMBAT'),
		('MODIFIER_ENABLE_BURNING_EYE_COMBAT_STRENGTH_PROPERTY', 'ModifierId', 'MODIFIER_BURNING_EYE_COMBAT_STRENGTH_PROPERTY'),
		('MODIFIER_BURNING_EYE_COMBAT_STRENGTH_ATTACHMENT', 'Key', 'BURNING_EYE_COMBAT'),
		('MODIFIER_BURNING_EYE_COMBAT_STRENGTH_ATTACHMENT', 'Amount', '1'),
		--------------------------------------------------------------
		('MODIFIER_BURNING_EYE_MOVEMENT_PROPERTY', 'Key', 'BURNING_EYE_MOVEMENT'),
		('MODIFIER_ENABLE_BURNING_EYE_MOVEMENT_PROPERTY', 'ModifierId', 'MODIFIER_BURNING_EYE_MOVEMENT_PROPERTY'),
		('MODIFIER_BURNING_EYE_MOVEMENT_ATTACHMENT', 'Key', 'BURNING_EYE_MOVEMENT'),
		('MODIFIER_BURNING_EYE_MOVEMENT_ATTACHMENT', 'Amount', '1'),
		-- CIVILIZATION TWO WORLDS ABILITY
		('MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY', 'Key', 'TWO_WORLDS_COMBAT'),
		('MODIFIER_ENABLE_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY', 'ModifierId', 'MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY'),
		('MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_ATTACHMENT', 'Key', 'TWO_WORLDS_COMBAT'),
		('MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_ATTACHMENT', 'Amount', '1');

INSERT INTO ModifierStrings(ModifierId, Context, Text)
VALUES	('MODIFIER_BURNING_EYE_COMBAT_STRENGTH_PROPERTY', 'Preview', 'LOC_TRAIT_MODIFIER_BURNING_EYE_COMBAT_DESCRIPTION'),
		('MODIFIER_TWO_WORLDS_COMBAT_STRENGTH_PROPERTY', 'Preview', 'LOC_TRAIT_MODIFIER_TWO_WORLDS_COMBAT_DESCRIPTION');